version: '3'
services:
  api-web: &app_base
    build:
      context: ../
      dockerfile: ./docker/rails/Dockerfile
    command: /bin/sh -c "sh script/docker_build_api-web.sh && ./run_development.sh"
    volumes:
      - ../rails/:/app:delegated
    ports:
      - '3000:3000'
    tty: true
    depends_on:
      - api-db
      - api-redis
    stdin_open: true
    environment:
      #これを設定しないと鍵関係で怒られて起動出来ない
      - "RAILS_ENV=development"
      - "RACK_ENV=development"
      - "MINIO_ACCESS_KEY=develop"
      - "MINIO_SECRET_KEY=password"
      - "SECRET_KEY_BASE=c4aa6c0a48a36077a701c12beeddebee"
      - "RAILS_MASTER_KEY=c4aa6c0a48a36077a701c12beeddebee"
      #ACTUAL_ENVを消せば、.envを読み込むので環境変数が変わる。
      - "ACTUAL_ENV=dev"
      - "DATABASE_HOST=api-db"
      - "DATABASE_PORT=3306"
      - "DATABASE_NAME=kaji_development"
      - "DATABASE_USERNAME=kaji"
      - "DATABASE_PASSWORD=root"
      - "REDIS_HOST=api-redis"
      - "REDIS_PORT=6379"
      - "REDIS_USERNAME=redis"
      - "REDIS_PASSWORD=redis"
      - "RAILS_LOG_TO_STDOUT=true"
      - "USE_DOCKER=true"
      - "ASSET_HOST=https://kaji-dev.s3.amazonaws.com"
      #とりあえずローカルはkajiのS3から持ってくる(minio使わない場合)
      - "S3_BUCKET=kaji-dev"
      - "WEBPACK_HOST=webpack"
      - "WEBPACK_ENDPOINT=webpack:3035"
      - "DEFAULT_HOST=https://localhost"
      - USE_AWS_S3
      - SECURE_SALT
      - SECURE_SALT_HASH
      # こっから下はpull_secretで読み込まれる
      #これは設定してなくてもreadはできる
      - AWS_REGION
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      # SNS関係
      - FACEBOOK_KEY
      - FACEBOOK_SECRET
      - TWITTER_API_KEY
      - TWITTER_API_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - LINE_KEY
      - LINE_SECRET
      - FCM_SERVER_KEY

  api-db:
    build:
      context: ../
      dockerfile: ./docker/mysql/Dockerfile
    restart: always
    env_file: ./mysql/.env
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '3306:3306'
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=kaji_development"
      - "MYSQL_USER=kaji"
      - "MYSQL_PASSWORD=root"
      - "default-authentication-plugin=mysql_native_password"

  api-redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  web:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api-web
    volumes:
      - ../rails/:/app:delegated
      - /app/tmp/cache

  api-s3:
    image: minio/minio:latest
    restart: always
    command: server /data
    volumes:
      - ./s3/data:/data:delegated
    environment:
      - "MINIO_ACCESS_KEY=develop"
      - "MINIO_SECRET_KEY=password"
    ports:
      - "9000:9000"

  createbuckets:
    image: minio/mc
    depends_on:
      - api-s3
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add kaji-dev http://api-s3:9000 develop password --api S3v4;
      /usr/bin/mc rm -r --force kaji-dev/kaji-dev;
      /usr/bin/mc mb kaji-dev/kaji-dev;
      /usr/bin/mc policy set download kaji-dev/kaji-dev;
      exit 0;
      "


  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui



  redis-client:
      image:  marian/rebrow
      links:
        - api-redis
      ports:
        - 5001:5001

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=api-db
        - PMA_USER=kaji
        - PMA_PASSWORD=root
      links:
        - api-db
      ports:
        - 3001:80
      volumes:
        - "./phpmyadmin/sessions:/sessions"
        - ./phpmyadmin/php.ini:/usr/local/etc/php/php.ini


  ngrok:
      image: shkoliar/ngrok:latest
      ports:
        - 4551:4551
      environment:
        - NGROK_AUTH_TOKEN
      command: >
        /bin/sh -c "
        ngrok authtoken $NGROK_AUTH_TOKEN;
        ngrok http web:80 -region=jp ;
        "

  webpack:
    build:
      context: ../
      dockerfile: ./docker/rails/Dockerfile
    command: /bin/sh -c "while :; do sleep 10; done"
    ports:
      - '3035:3035'
    tty: false
    volumes:
      - ../rails:/app:delegated
      # don't mount tmp directory
      - /app/tmp
    stdin_open: false
    environment:
      - "RAILS_ENV=development"
      - "RACK_ENV=development"
      #これを設定しないと鍵関係で怒られて起動出来ない
      - "SECRET_KEY_BASE=c4aa6c0a48a36077a701c12beeddebee"
      - "RAILS_MASTER_KEY=c4aa6c0a48a36077a701c12beeddebee"
      #とりあえずローカルはkajiのS3から持ってくる(minio使わない場合)
      - "MINIO_ACCESS_KEY=develop"
      - "MINIO_SECRET_KEY=password"
      - "S3_ACCESS_KEY_ID=AKIAQH7G22ST62H4I7OM"
      - "S3_SECRET_ACCESS_KEY=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"
      - "S3_BUCKET=kaji-dev"
      - "DATABASE_HOST=api-db"
      - "DATABASE_PORT=3306"
      - "DATABASE_NAME=kaji_development"
      - "DATABASE_USERNAME=kaji"
      - "DATABASE_PASSWORD=root"
      - "ACTUAL_ENV=dev"
      - "WEBPACK_HOST=webpack"
      - "WEBPACK_ENDPOINT=webpack:3035"
