#!/bin/bash

show_error () {
    echo "以下のコマンドで実行してください。"
    echo "# アプリケーションの起動"
    echo "$ ./exec app "
    echo "# バッチの起動"
    echo "$ ./exec batch "
    exit 1
}

if [ $# = 0 ]; then
    show_error
fi

if [ $1 != "app" ] && [ $1 != "batch" ]; then
    show_error
fi


if [ $1 = "app" ]; then
    docker-compose -f docker-compose.yml exec api-web bash
elif [ $1 = "batch" ]; then
    docker-compose -f docker-compose.yml exec api-batch bash
fi
