#!/bin/bash
#!/bin/bash

show_error () {
    echo "以下のコマンドで実行してください。"
    echo "# アプリケーションの起動"
    echo "$ USE_AWS_S3=true ./init app "
    echo "# バッチの起動"
    echo "$ USE_AWS_S3=true ./init batch "
    echo "# ツール(phpmyadmin, rebrow)の起動"
    echo "$ USE_AWS_S3=true ./init tool "
    exit 1
}

if [ $# = 0 ]; then
    show_error
fi

if [ $1 != "app" ] && [ $1 != "batch" ] && [ $1 != "tool" ]; then
    show_error
fi


if [ $1 = "app" ]; then


    # データベース削除
    rm -fr mysql/data
    #webpackのやつも削除
    rm -fr ../rails/tmp/cache/

    rm -fr ../rails/log/*

    rm -fr ../rails/node_modules


    docker-compose -f docker-compose.yml rm -f
    docker-compose -f docker-compose.yml down --rmi all


    # init build

    docker-compose -f docker-compose.yml up --build -d webpack
    #docker-compose -f docker-compose.yml exec webpack yarn install
    docker-compose -f docker-compose.yml exec webpack sh script/docker_delete_webpack.sh
    docker-compose -f docker-compose.yml exec webpack rails webpacker:install 
    docker-compose -f docker-compose.yml exec webpack sh script/docker_build_webpack.sh
    docker-compose -f docker-compose.yml exec -d webpack bin/webpack-dev-server && docker-compose -f docker-compose.yml up -d --build api-web api-db api-redis web api-s3 createbuckets mailhog

elif [ $1 = "batch" ]; then
    docker-compose -f docker-compose.yml up -d --build api-batch

elif [ $1 = "tool" ]; then
    docker-compose -f docker-compose.yml up -d --build phpmyadmin redis-client
fi